#!/bin/bash
#
# https://wiki.gentoo.org/wiki/Signed_kernel_module_support#Automatically_signing_kernel_modules_.28Portage.29

function sign_kernel_modules() {
	# This hook signs any out-of-tree kernel modules.
	if [[ -z "${MODULE_NAMES}" ]] ; then
		# The package does not seem to install any kernel modules.
		return
	fi

	# Get the signature algorithm used by the kernel.
	local module_sig_hash="$(grep -Po '(?<=CONFIG_MODULE_SIG_HASH=").*(?=")' /usr/src/linux/.config)"
	# Get the key file used by the kernel.
	local module_sig_key="$(grep -Po '(?<=CONFIG_MODULE_SIG_KEY=").*(?=")' /usr/src/linux/.config)"

	module_sig_key="${module_sig_key:-certs/signing_key.pem}"

	# Path to the key file or PKCS11 URI
	if [[ "${module_sig_key#pkcs11:}" == "${module_sig_key}" && "${module_sig_key#/}" == "${module_sig_key}" ]] ; then
		local key_path="/usr/src/linux/${module_sig_key}"
	else
		local key_path="${module_sig_key}"
	fi

	# Certificate path
	local cert_path=/usr/src/linux/certs/signing_key.x509

	# Sign all installed modules before merging.
	while IFS= read -r -d '' module ; do
		einfo "Signing ${module}"
		/usr/src/linux/scripts/sign-file "${module_sig_hash}" "${key_path}" "${cert_path}" "${module}"
	done < <(find "${D%/}/${INSDESTTREE#/}/" -type f -name "*.ko" -print0 )
}

sign_kernel_modules
