#!/bin/bash

for dir in help doc docs
do
	if [[ -d ${S}/$dir ]]; then
		einfo "Required DTDs for /$dir"
		find "${S}"/$dir -type f -name "*.xml" \
			-exec sed -nr '/DOCTYPE/ s:.*(-//.*?//EN).*:\1:p' {} \; \
			| uniq | xargs einfo
	fi
done
